{"timestamp":"2025-09-04T11:23:02.458717","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-04T11:23:02.459158","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/dynamic-airbyte-with-airflow.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-04T11:23:03.111654","level":"info","event":"Trying to parse the dbt project using dbt ls cache cosmos_cache__airbyte_dynamic_connection__my_project_dbt_group_11...","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:23:03.145703","level":"info","event":"Cosmos performance: time to calculate cache identifier cosmos_cache__airbyte_dynamic_connection__my_project_dbt_group_11 for current version: 0.02479920900077559","logger":"cosmos.cache"}
{"timestamp":"2025-09-04T11:23:03.145837","level":"info","event":"Cosmos performance [2b2e84620275|1461]: The cache size for cosmos_cache__airbyte_dynamic_connection__my_project_dbt_group_11 is 4335","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:23:03.145960","level":"info","event":"Cosmos performance: Cache hit for cosmos_cache__airbyte_dynamic_connection__my_project_dbt_group_11 - aad8d04d72ff7b6917b24f4cd2f34a0b,d41d8cd98f00b204e9800998ecf8427e","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:23:03.146325","level":"info","event":"Total nodes: 6","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:23:03.146353","level":"info","event":"Total filtered nodes: 6","logger":"cosmos.dbt.graph"}
{"timestamp":"2025-09-04T11:23:03.146395","level":"info","event":"Cosmos performance (airbyte_dynamic_connection__my_project_dbt_group_11) -  [2b2e84620275|1461]: It took 0.0348s to parse the dbt project for DAG using LoadMode.DBT_LS_CACHE","logger":"cosmos.converter"}
{"timestamp":"2025-09-04T11:23:03.146727","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:23:03.147281","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:23:03.148059","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:23:03.148493","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:23:03.148843","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:23:03.149190","level":"info","event":"Project /opt/airflow/dbt/my_project_dbt does not have {'dependencies.yml', 'packages.yml'}","logger":"cosmos.dbt.project"}
{"timestamp":"2025-09-04T11:23:03.149482","level":"info","event":"Cosmos performance (airbyte_dynamic_connection__my_project_dbt_group_11) - [2b2e84620275|1461]: It took 0.0031s to build the Airflow DAG.","logger":"cosmos.converter"}
{"timestamp":"2025-09-04T11:23:03.149819","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/pydantic/main.py:463: UserWarning: Pydantic serializer warnings:\n  PydanticSerializationUnexpectedValue(Expected `str` - serialized value may not be as expected [input_value={'version': 'aad8d04d72ff...y_project_dbt_group_11'}, input_type=dict])\n  return self.__pydantic_serializer__.to_python(\n","logger":"py.warnings"}
{"timestamp":"2025-09-04T11:23:03.163305Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:03.163458Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:03.163607Z","level":"info","event":"Current task name:my_project_dbt_group_11.stg_weather_data_run","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:03.163772Z","level":"info","event":"Dag name:airbyte_dynamic_connection","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:03.940652","level":"info","event":"dbtRunner is available. Using dbtRunner for invoking dbt.","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:23:03.941397","level":"info","event":"Cloning project to writable temp directory /tmp/tmpv1jq6jt8 from /opt/airflow/dbt/my_project_dbt","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:23:03.943073","level":"info","event":"Partial parse is enabled and the latest partial parse file is /tmp/cosmos/airbyte_dynamic_connection__my_project_dbt_group_11/target/partial_parse.msgpack","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:23:03.948247","level":"info","event":"Profile caching is enable.","logger":"cosmos.config"}
{"timestamp":"2025-09-04T11:23:03.956783","level":"info","event":"Connection Retrieved 'test-airbyte-and-dbt-with-airflow'","logger":"airflow.hooks.base"}
{"timestamp":"2025-09-04T11:23:03.957344","level":"info","event":"Profile found in cache using profile: /tmp/cosmos/profile/922021775909dd134e724f780b41e87fc6d4989e8d9e38bd82f43f7a68edaf2a/profiles.yml.","logger":"cosmos.config"}
{"timestamp":"2025-09-04T11:23:03.957645","level":"info","event":"Trying to run dbtRunner with:\n ['run', '--select', 'stg_weather_data', '--project-dir', '/tmp/tmpv1jq6jt8', '--profiles-dir', '/tmp/cosmos/profile/922021775909dd134e724f780b41e87fc6d4989e8d9e38bd82f43f7a68edaf2a', '--profile', 'dbt_postgres_profile', '--target', 'dev', '--no-static-parser']\n in /tmp/tmpv1jq6jt8","logger":"cosmos.dbt.runner"}
{"timestamp":"2025-09-04T11:23:03.981068Z","level":"info","event":"\u001b[0m11:23:03  Running with dbt=1.8.2","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.285056Z","level":"info","event":"\u001b[0m11:23:04  Registered adapter: postgres=1.8.2","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.716285Z","level":"info","event":"\u001b[0m11:23:04  Found 5 models, 1 source, 428 macros","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.717191Z","level":"info","event":"\u001b[0m11:23:04","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.744993Z","level":"info","event":"\u001b[0m11:23:04","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.745172Z","level":"info","event":"\u001b[0m11:23:04  Finished running  in 0 hours 0 minutes and 0.03 seconds (0.03s).","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.745475Z","level":"info","event":"\u001b[0m11:23:04  Encountered an error:","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.745615Z","level":"info","event":"Database Error","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.745694Z","level":"info","event":"  connection to server at \"host.docker.internal\" (192.168.65.254), port 5391 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.746018Z","level":"info","event":"  \tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:04.746082Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.953764","level":"info","event":"Inlets: []","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:23:05.953881","level":"info","event":"Outlets: []","logger":"cosmos.operators.base"}
{"timestamp":"2025-09-04T11:23:05.953980","level":"info","event":"Assigning outlets with DatasetAlias in Airflow 3","logger":"cosmos.operators.local"}
{"timestamp":"2025-09-04T11:23:05.956211","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CosmosDbtRunError","exc_value":"dbt invocation did not complete with unhandled error: Database Error\n  connection to server at \"host.docker.internal\" (192.168.65.254), port 5391 failed: Connection refused\n  \tIs the server running on that host and accepting TCP/IP connections?\n  ","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":918,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1213,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py","lineno":310,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py","lineno":851,"name":"build_and_run_cmd"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py","lineno":648,"name":"run_command"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py","lineno":258,"name":"handle_exception_dbt_runner"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/cosmos/dbt/runner.py","lineno":109,"name":"handle_exception_if_needed"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-04T11:23:05.967429Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.967592Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.967701Z","level":"info","event":"Task:<Task(DbtRunLocalOperator): my_project_dbt_group_11.stg_weather_data_run>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.967788Z","level":"info","event":"Failure caused by dbt invocation did not complete with unhandled error: Database Error","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.967879Z","level":"info","event":"  connection to server at \"host.docker.internal\" (192.168.65.254), port 5391 failed: Connection refused","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.967977Z","level":"info","event":"  \tIs the server running on that host and accepting TCP/IP connections?","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.968061Z","level":"info","event":"","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.986411Z","level":"error","event":"/usr/local/lib/python3.12/multiprocessing/resource_tracker.py:279: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-04T11:23:05.989240Z","level":"error","event":"  warnings.warn('resource_tracker: There appear to be %d '","chan":"stderr","logger":"task"}
